# -*- coding: utf-8 -*-
"""Aggregate all calculator definitions."""
from calcs_part1 import PART1
from calcs_part2 import PART2
from calcs_part3 import PART3
from calcs_part4 import PART4
from calcs_part5 import PART5
from calcs_part6 import PART6
from calcs_part7 import PART7
from calcs_part8 import PART8
from calcs_part9 import PART9
from calcs_part10 import PART10
from calcs_part11 import PART11
from calcs_part12 import PART12
from calcs_part13 import PART13
from calcs_part14 import PART14
from calcs_part15 import PART15
from calcs_part16 import PART16
from calcs_part17 import PART17
from calcs_leasebuy import LEASEBUY
from calcs_rentbuy import RENTBUY
from calcs_debtinvest import DEBTINVEST
from calcs_mortgageterm import MORTGAGETERM
from calcs_autoloan import AUTOLOAN
from calcs_socialsecurity import SOCIALSECURITY
from calcs_rothtrad import ROTHTRAD
from calcs_hsa import HSA
from calcs_taxbracket import TAXBRACKET
from calcs_setax import SETAX
from calcs_bonustax import BONUSTAX
from calcs_rmd import RMD
from calcs_balancetransfer import BALXFER
from calcs_rothconversion import ROTHCONV
from calcs_heloc import HELOC
from calcs_lifeinsurance import LIFEINS
from calcs_armfixed import ARMFIXED
from calcs_pmi import PMI
from calcs_closingcosts import CLOSING
from calcs_cdladder import CDLADDER
from calcs_recast import RECAST
from calcs_401kwithdrawal import K401WD
from calcs_pensionlump import PENSIONLUMP
from calcs_quarterlytax import QUARTERLY
from calcs_solo401k import SOLO401K
from calcs_withholding import WITHHOLDING
from calcs_daycare import DAYCARE
from calcs_rsu import RSU
from calcs_studentrefi import STUDENTREFI
from calcs_propertytax import PROPTAX
from calcs_collegeroi import COLLEGEROI
from calcs_payday import PAYDAY

CALCS = PART1 + PART2 + PART3 + PART4 + PART5 + PART6 + PART7 + PART8 + PART9 + PART10 + PART11 + PART12 + PART13 + PART14 + PART15 + PART16 + PART17 + LEASEBUY + RENTBUY + DEBTINVEST + MORTGAGETERM + AUTOLOAN + SOCIALSECURITY + ROTHTRAD + HSA + TAXBRACKET + SETAX + BONUSTAX + RMD + BALXFER + ROTHCONV + HELOC + LIFEINS + ARMFIXED + PMI + CLOSING + CDLADDER + RECAST + K401WD + PENSIONLUMP + QUARTERLY + SOLO401K + WITHHOLDING + DAYCARE + RSU + STUDENTREFI + PROPTAX + COLLEGEROI + PAYDAY
